# Indentation settings
defaultIndent: "  "
indentation: "  "

# Backup settings
onlyOneBackUp: 1
maxNumberOfBackUps: 5
overwriteIfDifferent: 1

# Trailing whitespace
removeTrailingWhitespace:
  beforeProcessing: 0
  afterProcessing: 1
