name: check

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Nix build cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix flake check
        run: nix flake check --print-build-logs

      - name: Build default package
        run: nix build .#default --print-build-logs
